language: python
python:
  - "3.12"

install:
  - pip install -r requirements.txt

before_script:
  - black --check .
  - flake8 .

script:
  - coverage run manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "swe1-app2"
  env: "swe1-app2"
  bucket_name: "elasticbeanstalk-us-east-1-386104178815"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    branch: main